basePath: /v1
definitions:
  handlers.AccountRequest:
    properties:
      access_token:
        type: string
      expires_at:
        type: integer
      provider:
        type: string
      provider_account_id:
        type: string
    type: object
  handlers.ServerInfo:
    properties:
      environment:
        type: string
      version:
        type: string
    type: object
  handlers.ServerStatus:
    description: Response for the health check
    properties:
      status:
        description: Status is the health status of the service
        type: string
      system_info:
        allOf:
        - $ref: '#/definitions/handlers.ServerInfo'
        description: SystemInfo contains information about the system
    type: object
  models.Subtask:
    properties:
      completed:
        type: boolean
      createdAt:
        type: string
      isHidden:
        type: boolean
      subtaskID:
        type: string
      title:
        type: string
    type: object
  models.Task:
    properties:
      completed:
        type: boolean
      contentType:
        type: string
      createdAt:
        type: string
      isHidden:
        type: boolean
      kind:
        type: string
      subtasks:
        items:
          $ref: '#/definitions/models.Subtask'
        type: array
      taskID:
        type: string
      title:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      image:
        type: string
      name:
        type: string
      userID:
        type: string
    type: object
  problem.Problem:
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: nishojib@kupolog.com
    name: nishojib
    url: https://api.kupolog.com/support
  description: This is an API for the Kupolog app.
  license:
    name: MIT
    url: https://opensource.org/license/mit
  termsOfService: https://api.kupolog.com/terms
  title: Swagger Kupolog API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: takes a google or discord account request verifies the account
        and returns a token
      parameters:
      - description: account request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.AccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              token:
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                type: object
              user:
                $ref: '#/definitions/models.User'
            type: object
        "400":
          description: Bad Request
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
      summary: login
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: refreshes the access token for the user
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              access_token:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
      security:
      - Bearer: []
      summary: refresh token
      tags:
      - auth
  /auth/revoke:
    post:
      consumes:
      - application/json
      description: revokes the refresh token for the user
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
      security:
      - Bearer: []
      summary: revoke token
      tags:
      - auth
  /dailies/daily:
    get:
      description: Get the daily tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              dailies:
                items:
                  $ref: '#/definitions/models.Task'
                type: array
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
      summary: Daily tasks
      tags:
      - dailies
  /dailies/subtasks/{subtaskID}:
    put:
      consumes:
      - application/json
      description: Toggle the subtask
      parameters:
      - description: Subtask ID
        in: path
        name: subtaskID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              task:
                $ref: '#/definitions/models.Subtask'
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
      summary: Toggle subtask
      tags:
      - dailies
  /dailies/tasks/{taskID}:
    put:
      consumes:
      - application/json
      description: Toggle the task
      parameters:
      - description: Task ID
        in: path
        name: taskID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              task:
                $ref: '#/definitions/models.Task'
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
      summary: Toggle task
      tags:
      - dailies
  /dailies/weekly:
    get:
      description: Get the weekly tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              weeklies:
                items:
                  $ref: '#/definitions/models.Task'
                type: array
            type: object
        "404":
          description: Not Found
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string
            type: object
      summary: Weekly tasks
      tags:
      - dailies
  /health:
    get:
      description: Checks the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ServerStatus'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/problem.Problem'
      summary: Health check
      tags:
      - health
securityDefinitions:
  Bearer:
    description: '"Type ''Bearer TOKEN'' to correctly set the API Key"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
