name: Weekly cron
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 2'
    - cron: '0 15 * * *'

jobs:
  style:
    name: Cron
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build go app for linux
        run: GOOS=linux GOARCH=amd64 go build -o ./bin/linux/cron ./cmd/crons
        working-directory: ./backend

      - name: Run cron app for weekly
        run: ./bin/linux/cron -env production -kind weekly
        if: github.event.schedule == '0 8 * * 2'
        working-directory: ./backend
        env:
          DB_DSN: ${{ secrets.DB_DSN }}

      - name: Run cron app for daily
        run: ./bin/linux/cron -env production -kind daily
        if: github.event.schedule == '0 15 * * *'
        working-directory: ./backend
        env:
          DB_DSN: ${{ secrets.DB_DSN }}
